# Generated by Django 3.0.6 on 2020-06-04 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=512)),
                ('content', models.TextField(max_length=4096)),
                ('image', models.FileField(upload_to='upload/')),
                ('published', models.DateTimeField(default=datetime.datetime(2020, 6, 4, 19, 27, 36))),
                ('source', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forex',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
        migrations.DeleteModel(
            name='Crypto',
        ),
        migrations.DeleteModel(
            name='Forex',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
